<?php
/**
 * Plugin tool registry — maps each plugin slug to its tool IDs and labels.
 * Used by sitemap.php to emit ?tool= URLs for individual tool pages.
 * Add new entries here whenever a plugin gains new tools.
 */
return [

    'json-tools' => [
        ['formatter',   'JSON Formatter'],
        ['beautifier',  'JSON Beautifier'],
        ['minifier',    'JSON Minifier'],
        ['validator',   'JSON Validator'],
        ['parser',      'JSON Parser'],
        ['viewer',      'JSON Viewer'],
        ['prettyprint', 'Pretty Print'],
        ['sortkeys',    'Sort Keys'],
        ['flatten',     'Flatten JSON'],
        ['jsonpath',    'JSONPath Query'],
        ['diff',        'JSON Diff'],
        ['escape',      'JSON Escape'],
        ['unescape',    'JSON Unescape'],
        ['json2csv',    'JSON to CSV'],
        ['csv2json',    'CSV to JSON'],
        ['json2xml',    'JSON to XML'],
        ['xml2json',    'XML to JSON'],
        ['json2yaml',   'JSON to YAML'],
        ['yaml2json',   'YAML to JSON'],
    ],

    'encoding-toolkit' => [
        ['b64enc',      'Base64 Encoder'],
        ['b64dec',      'Base64 Decoder'],
        ['b64imgenc',   'Image to Base64'],
        ['b64imgdec',   'Base64 to Image'],
        ['b64urlenc',   'Base64url Encoder'],
        ['b64urldec',   'Base64url Decoder'],
        ['urlenc',      'URL Encoder'],
        ['urldec',      'URL Decoder'],
        ['qbuild',      'Query Builder'],
        ['qparse',      'Query Parser'],
        ['urlparse',    'URL Parser'],
        ['urlextract',  'URL Extractor'],
        ['urlclean',    'URL Cleaner'],
        ['urlsplit',    'URL Split'],
        ['ascii',       'ASCII Table'],
        ['unicode',     'Unicode Lookup'],
        ['utf8',        'UTF-8 Encoder'],
        ['utf16',       'UTF-16 Encoder'],
        ['binenc',      'Binary Encoder'],
        ['bindec',      'Binary Decoder'],
        ['octal',       'Octal Converter'],
        ['decimal',     'Decimal Converter'],
        ['hex',         'Hex Converter'],
        ['charcode',    'Character Code'],
        ['md5',         'MD5 Hash'],
        ['crc32',       'CRC32'],
        ['sha1',        'SHA-1 Hash'],
        ['sha256',      'SHA-256 Hash'],
        ['sha384',      'SHA-384 Hash'],
        ['sha512',      'SHA-512 Hash'],
        ['hmac',        'HMAC Generator'],
    ],

    'security-toolkit' => [
        ['md5',         'MD5 Generator'],
        ['sha1',        'SHA-1 Generator'],
        ['sha224',      'SHA-224 Generator'],
        ['sha256',      'SHA-256 Generator'],
        ['sha384',      'SHA-384 Generator'],
        ['sha512',      'SHA-512 Generator'],
        ['crc32',       'CRC32 Checksum'],
        ['ripemd160',   'RIPEMD-160'],
        ['whirlpool',   'Whirlpool Hash'],
        ['pwgen',       'Password Generator'],
        ['pwhash',      'Password Hash'],
        ['pwcheck',     'Password Strength'],
        ['bcrypt',      'BCrypt Hash'],
        ['jwtdec',      'JWT Decoder'],
        ['jwtenc',      'JWT Encoder'],
        ['jwtval',      'JWT Validator'],
        ['jwtinsp',     'JWT Inspector'],
        ['jwtexp',      'JWT Expiry Checker'],
        ['hmac',        'HMAC Generator'],
        ['filehash',    'File Hash Calculator'],
        ['hashverify',  'Hash Verifier'],
        ['tokengen',    'Token Generator'],
    ],

    'regex-toolkit' => [
        ['tester',      'Regex Tester'],
        ['replace',     'Regex Replace'],
        ['extractor',   'Regex Extractor'],
        ['highlighter', 'Regex Highlighter'],
        ['explainer',   'Regex Explainer'],
        ['validator',   'Regex Validator'],
        ['namedgroups', 'Named Groups'],
        ['generator',   'Regex Generator'],
        ['patterns',    'Pattern Library'],
        ['cheatsheet',  'Regex Cheat Sheet'],
    ],

    'xml-tools' => [
        ['formatter',   'XML Formatter'],
        ['beautifier',  'XML Beautifier'],
        ['minifier',    'XML Minifier'],
        ['validator',   'XML Validator'],
        ['viewer',      'XML Viewer'],
        ['escape',      'XML Escape'],
        ['unescape',    'XML Unescape'],
        ['xml2csv',     'XML to CSV'],
        ['csv2xml',     'CSV to XML'],
        ['diff',        'XML Diff'],
    ],

    'yaml-tools' => [
        ['formatter',   'YAML Formatter'],
        ['validator',   'YAML Validator'],
        ['viewer',      'YAML Viewer'],
        ['sortkeys',    'Sort Keys'],
        ['flatten',     'Flatten YAML'],
        ['diff',        'YAML Diff'],
        ['escape',      'YAML Escape'],
        ['unescape',    'YAML Unescape'],
        ['yaml2json',   'YAML to JSON'],
        ['json2yaml',   'JSON to YAML'],
        ['yaml2csv',    'YAML to CSV'],
        ['csv2yaml',    'CSV to YAML'],
    ],

];
