<?php
/**
 * Internet Speed Test — PHP API backend
 * Accessible at /plugins/internet-speed-test/api?action=...
 *
 * Actions:
 *   ping          — Latency probe; returns immediately with server timestamp.
 *   download      — Streams a random-byte payload of ?size= bytes.
 *   upload        — Accepts and discards POST body; returns received bytes.
 *   myip          — Detects client IP + basic server environment info.
 *   dns_time      — Server-side DNS resolution timing for a test domain.
 *   http_timing   — HEAD request timing to a well-known CDN endpoint.
 *   report        — Generates an ANSI-coloured terminal report from JSON results.
 */
defined('AWAN') or require_once __DIR__ . '/../../_bootstrap.php';

header('X-Robots-Tag: noindex');
header('Cache-Control: no-store, no-cache');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET, POST, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type');

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') { http_response_code(204); exit; }

$action = trim($_GET['action'] ?? '');
if (!$action) {
    header('Content-Type: application/json; charset=utf-8');
    echo json_encode(['error' => 'No action specified']);
    exit;
}

/* ─── ANSI helpers ───────────────────────────────────────────────────────── */
define('IST_A0',   "\033[0m");
define('IST_AB',   "\033[1m");
define('IST_AD',   "\033[2m");
define('IST_ACY',  "\033[36m");
define('IST_ABCY', "\033[96m");
define('IST_AGR',  "\033[32m");
define('IST_ABGR', "\033[92m");
define('IST_ARE',  "\033[31m");
define('IST_ABRE', "\033[91m");
define('IST_AYE',  "\033[33m");
define('IST_ABYE', "\033[93m");
define('IST_AMA',  "\033[35m");
define('IST_ABMA', "\033[95m");
define('IST_AGY',  "\033[90m");
define('IST_AWH',  "\033[97m");
define('IST_ABBL', "\033[94m");
define('IST_W',    66);

function ist_apad(string $s, int $w): string {
    $plain = preg_replace('/\033\[[0-9;]*m/', '', $s);
    return $s . str_repeat(' ', max(0, $w - mb_strlen($plain)));
}
function ist_row(string $label, string $value): string {
    return '  ' . IST_ABYE . IST_AB . str_pad($label, 22) . IST_A0 . IST_AWH . $value . IST_A0 . "\n";
}
function ist_sec(string $title): string {
    $ruleLen = max(4, IST_W - mb_strlen($title) - 3);
    return "\n" . IST_ABCY . IST_AB . '◆' . IST_A0 . ' ' . IST_AWH . IST_AB . $title . IST_A0
         . '  ' . IST_AGY . str_repeat('─', $ruleLen) . IST_A0 . "\n\n";
}
function ist_bar(float $val, float $max, int $width = 20): string {
    $filled = $max > 0 ? (int)min($width, round($val / $max * $width)) : 0;
    return str_repeat('█', $filled) . IST_AGY . str_repeat('░', $width - $filled) . IST_A0;
}
function ist_grade_clr(string $g): string {
    return match($g) { 'A+', 'A' => IST_ABGR, 'B' => IST_ABYE, 'C' => IST_AYE, default => IST_ABRE };
}

/* ═══════════════════════════════════════════════════════════════════════════
 * ★ DEVELOPER TWEAKABLE — REPORT HEADER
 *   Edit ist_term_header() to customise the top banner of the terminal report.
 * ═══════════════════════════════════════════════════════════════════════════ */
function ist_term_header(array $r): string {
    $w    = IST_W;
    $line = str_repeat('═', $w);
    $ts   = $r['timestamp'] ?? date('Y-m-d H:i:s');
    $host = $_SERVER['HTTP_HOST'] ?? 'awantools.site';

    $title  = 'INTERNET SPEED TEST — NETWORK DIAGNOSTICS REPORT';
    $pad    = max(0, (int)(($w - mb_strlen($title)) / 2));

    return
        IST_ABCY . IST_AB . '╔' . str_repeat('═', $w) . '╗' . IST_A0 . "\n" .
        IST_ABCY . IST_AB . '║' . IST_A0 . str_repeat(' ', $pad) . IST_AWH . IST_AB . $title . IST_A0 . str_repeat(' ', max(0, $w - $pad - mb_strlen($title))) . IST_ABCY . IST_AB . '║' . IST_A0 . "\n" .
        IST_ABCY . IST_AB . '╠' . str_repeat('═', $w) . '╣' . IST_A0 . "\n" .
        IST_ABCY . IST_AB . '║' . IST_A0 . ist_apad('  ' . IST_AGY . 'Platform ' . IST_A0 . IST_AWH . 'Awan Tools — awantools.site' . IST_A0, $w) . IST_ABCY . IST_AB . '║' . IST_A0 . "\n" .
        IST_ABCY . IST_AB . '║' . IST_A0 . ist_apad('  ' . IST_AGY . 'Server   ' . IST_A0 . IST_AWH . $host . IST_A0, $w) . IST_ABCY . IST_AB . '║' . IST_A0 . "\n" .
        IST_ABCY . IST_AB . '║' . IST_A0 . ist_apad('  ' . IST_AGY . 'Generated' . IST_A0 . IST_AWH . $ts . IST_A0, $w) . IST_ABCY . IST_AB . '║' . IST_A0 . "\n" .
        IST_ABCY . IST_AB . '╚' . str_repeat('═', $w) . '╝' . IST_A0 . "\n";
}

/* ★ DEVELOPER TWEAKABLE — REPORT FOOTER */
function ist_term_footer(): string {
    $w    = IST_W;
    $msg  = 'Generated by Awan Tools Internet Speed Test · awantools.site';
    $pad  = max(0, (int)(($w - mb_strlen($msg)) / 2));
    return
        "\n" . IST_AGY . str_repeat('─', $w) . IST_A0 . "\n" .
        str_repeat(' ', $pad) . IST_AGY . $msg . IST_A0 . "\n\n";
}

/* ─── HTTP fetch helper ──────────────────────────────────────────────────── */
function ist_fetch(string $url, array $opts = []): array {
    $timeout = (int)($opts['timeout'] ?? 10);
    $method  = strtoupper($opts['method'] ?? 'HEAD');

    if (function_exists('curl_init')) {
        $ch = curl_init();
        curl_setopt_array($ch, [
            CURLOPT_URL            => $url,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_TIMEOUT        => $timeout,
            CURLOPT_FOLLOWLOCATION => false,
            CURLOPT_CUSTOMREQUEST  => $method,
            CURLOPT_HEADER         => true,
            CURLOPT_SSL_VERIFYPEER => false,
            CURLOPT_SSL_VERIFYHOST => 0,
            CURLOPT_USERAGENT      => 'Mozilla/5.0 (compatible; AwanTools/1.0; +https://awantools.site)',
            CURLOPT_NOBODY         => ($method === 'HEAD'),
        ]);
        $raw   = curl_exec($ch);
        $info  = curl_getinfo($ch);
        $errno = curl_errno($ch);
        curl_close($ch);
        if ($errno) return ['error' => curl_error($ch), 'code' => 0, 'time' => 0];
        return ['body' => substr($raw, $info['header_size']), 'code' => (int)$info['http_code'], 'time' => (float)$info['total_time'] * 1000, 'error' => null];
    }

    $ctx  = stream_context_create(['http' => ['method' => $method, 'timeout' => $timeout, 'ignore_errors' => true], 'ssl' => ['verify_peer' => false]]);
    $t0   = microtime(true);
    @file_get_contents($url, false, $ctx);
    $t1   = microtime(true);
    return ['code' => 0, 'time' => ($t1 - $t0) * 1000, 'error' => null];
}

/* ═══════════════════════════════════════════════════════════════════════════
 * ACTION DISPATCH
 * ═══════════════════════════════════════════════════════════════════════════ */

/* ── ping ───────────────────────────────────────────────────────────────── */
if ($action === 'ping') {
    header('Content-Type: application/json; charset=utf-8');
    echo json_encode(['ok' => true, 'ts' => microtime(true), 'server_time' => date('c')]);
    exit;
}

/* ── download (legacy single-chunk) ────────────────────────────────────── */
if ($action === 'download') {
    $size = min((int)($_GET['size'] ?? 1048576), 8388608); // max 8MB per chunk
    header('Content-Type: application/octet-stream');
    header('Content-Length: ' . $size);
    header('Cache-Control: no-store');
    header('X-Content-Size: ' . $size);

    $chunk  = 65536;
    $sent   = 0;
    $rndBuf = random_bytes(min($chunk, $size));
    while ($sent < $size) {
        $toSend = min($chunk, $size - $sent);
        echo substr($rndBuf, 0, $toSend);
        $sent += $toSend;
        if (connection_aborted()) break;
    }
    exit;
}

/* ── download_stream (parallel streaming — high accuracy) ───────────────── */
if ($action === 'download_stream') {
    $duration = (float)min((float)($_GET['duration'] ?? 10), 30);

    header('Content-Type: application/octet-stream');
    header('Content-Encoding: identity');   // prevent any gzip/deflate that hides true byte count
    header('Cache-Control: no-store, no-cache');
    header('X-Accel-Buffering: no');
    header('X-Content-Type-Options: nosniff');

    while (ob_get_level() > 0) { @ob_end_clean(); }

    // XOR-based buffer: each write is unique, prevents any transparent compression
    $seed  = random_bytes(65536);
    $mask  = random_bytes(65536);
    $xored = $seed ^ $mask;
    $buf   = str_repeat($xored, 64);   // 4 MB per write

    $endTime = microtime(true) + $duration;
    $iter    = 0;

    while (microtime(true) < $endTime) {
        echo $buf;
        $iter++;
        if ($iter % 4 === 0) {
            @ob_flush();
            @flush();
            if (connection_aborted()) break;
        }
    }
    exit;
}

/* ── upload ─────────────────────────────────────────────────────────────── */
if ($action === 'upload') {
    header('Content-Type: application/json; charset=utf-8');
    // Always count actual bytes received via fread — never trust CONTENT_LENGTH
    // (proxies and built-in server can report it before the body is fully read).
    $bytes = 0;
    $input = fopen('php://input', 'rb');
    while (!feof($input)) {
        $chunk  = fread($input, 131072);
        $bytes += strlen($chunk);
    }
    fclose($input);
    echo json_encode(['ok' => true, 'received' => $bytes, 'ts' => microtime(true)]);
    exit;
}

/* ── myip ───────────────────────────────────────────────────────────────── */
if ($action === 'myip') {
    header('Content-Type: application/json; charset=utf-8');

    // Detect real IP from headers (shared hosting / proxy aware)
    $ip = '';
    foreach (['HTTP_CF_CONNECTING_IP', 'HTTP_X_REAL_IP', 'HTTP_X_FORWARDED_FOR', 'REMOTE_ADDR'] as $k) {
        if (!empty($_SERVER[$k])) {
            $candidate = trim(explode(',', $_SERVER[$k])[0]);
            if (filter_var($candidate, FILTER_VALIDATE_IP)) { $ip = $candidate; break; }
        }
    }

    $isIPv6    = filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_IPV6) !== false;
    $isPrivate = filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_NO_PRIV_RANGE | FILTER_FLAG_NO_RES_RANGE) === false;

    // Server environment
    $phpVer   = PHP_VERSION;
    $sapi     = php_sapi_name();
    $server   = $_SERVER['SERVER_SOFTWARE'] ?? 'Unknown';
    $hostname = gethostname() ?: 'Unknown';
    $serverIp = gethostbyname($hostname);

    // Check IPv6 support server-side
    $ipv6Support = defined('AF_INET6');

    // ISP / geo lookup via ip-api.com (free, no key required)
    $isp = [];
    if ($ip && !$isPrivate) {
        $ctx = stream_context_create(['http' => ['timeout' => 3, 'ignore_errors' => true]]);
        $raw = @file_get_contents(
            'http://ip-api.com/json/' . urlencode($ip) . '?fields=status,country,countryCode,regionName,city,isp,org,as',
            false, $ctx
        );
        if ($raw) {
            $parsed = @json_decode($raw, true);
            if (!empty($parsed) && ($parsed['status'] ?? '') === 'success') {
                $isp = [
                    'isp'          => $parsed['isp']        ?? '',
                    'org'          => $parsed['org']         ?? '',
                    'as'           => $parsed['as']          ?? '',
                    'country'      => $parsed['country']     ?? '',
                    'country_code' => $parsed['countryCode'] ?? '',
                    'region'       => $parsed['regionName']  ?? '',
                    'city'         => $parsed['city']        ?? '',
                ];
            }
        }
    }

    echo json_encode([
        'ip'           => $ip,
        'is_ipv6'      => $isIPv6,
        'is_private'   => $isPrivate,
        'ipv6_support' => $ipv6Support,
        'server'       => $server,
        'php'          => $phpVer,
        'hostname'     => $hostname,
        'server_ip'    => $serverIp !== $hostname ? $serverIp : null,
        'timestamp'    => microtime(true),
        'date'         => date('c'),
        'isp'          => $isp,
    ]);
    exit;
}

/* ── dns_time ───────────────────────────────────────────────────────────── */
if ($action === 'dns_time') {
    header('Content-Type: application/json; charset=utf-8');

    $testDomains = ['cloudflare.com', 'google.com', 'github.com'];
    $results = [];
    foreach ($testDomains as $domain) {
        $t0 = microtime(true);
        $resolved = @dns_get_record($domain, DNS_A);
        $t1 = microtime(true);
        $results[] = [
            'domain'  => $domain,
            'time_ms' => round(($t1 - $t0) * 1000, 2),
            'resolved'=> !empty($resolved),
            'ip'      => $resolved[0]['ip'] ?? null,
        ];
    }

    $avg = count($results) ? round(array_sum(array_column($results, 'time_ms')) / count($results), 2) : null;
    echo json_encode(['results' => $results, 'avg_ms' => $avg, 'timestamp' => microtime(true)]);
    exit;
}

/* ── http_timing ────────────────────────────────────────────────────────── */
if ($action === 'http_timing') {
    header('Content-Type: application/json; charset=utf-8');

    // Measure timing to well-known CDN endpoints
    $endpoints = [
        ['name' => 'Cloudflare', 'url' => 'https://1.1.1.1/'],
        ['name' => 'Google DNS',  'url' => 'https://8.8.8.8/'],
    ];

    $results = [];
    foreach ($endpoints as $ep) {
        $t0  = microtime(true);
        $res = ist_fetch($ep['url'], ['timeout' => 5, 'method' => 'HEAD']);
        $t1  = microtime(true);
        $results[] = [
            'name'    => $ep['name'],
            'url'     => $ep['url'],
            'time_ms' => round($res['time'] > 0 ? $res['time'] : ($t1 - $t0) * 1000, 2),
            'code'    => $res['code'],
            'error'   => $res['error'],
        ];
    }

    echo json_encode(['results' => $results, 'timestamp' => microtime(true)]);
    exit;
}

/* ── report ─────────────────────────────────────────────────────────────── */
if ($action === 'report') {
    header('Content-Type: text/plain; charset=utf-8');
    header('X-Content-Type-Options: nosniff');

    // Accept results from POST body (JSON) or GET params
    $body = file_get_contents('php://input');
    $r    = $body ? (json_decode($body, true) ?? []) : [];

    // Merge GET params as fallback
    $r = array_merge([
        'download'    => $_GET['dl']   ?? null,
        'upload'      => $_GET['ul']   ?? null,
        'ping'        => $_GET['ping'] ?? null,
        'jitter'      => $_GET['jitter'] ?? null,
        'packet_loss' => $_GET['loss'] ?? null,
        'grade'       => $_GET['grade'] ?? null,
        'score'       => $_GET['score'] ?? null,
        'timestamp'   => $_GET['ts']   ?? date('Y-m-d H:i:s'),
        'ip'          => $_GET['ip']   ?? null,
    ], $r);

    $w = IST_W;

    $out = ist_term_header($r);

    /* Connection Results */
    $out .= ist_sec('Connection Results');

    $dl   = isset($r['download'])    ? (float)$r['download']    : null;
    $ul   = isset($r['upload'])      ? (float)$r['upload']      : null;
    $ping = isset($r['ping'])        ? (float)$r['ping']        : null;
    $jit  = isset($r['jitter'])      ? (float)$r['jitter']      : null;
    $loss = isset($r['packet_loss']) ? (float)$r['packet_loss'] : null;

    if ($dl !== null) {
        $dlClr = $dl >= 100 ? IST_ABGR : ($dl >= 25 ? IST_ABYE : IST_ABRE);
        $dlBar = ist_bar($dl, 1000);
        $out  .= ist_row('Download Speed', $dlClr . number_format($dl, 1) . ' Mbps' . IST_A0 . '  ' . $dlClr . $dlBar . IST_A0);
    }
    if ($ul !== null) {
        $ulClr = $ul >= 50 ? IST_ABGR : ($ul >= 10 ? IST_ABYE : IST_ABRE);
        $ulBar = ist_bar($ul, 500);
        $out  .= ist_row('Upload Speed',   $ulClr . number_format($ul, 1) . ' Mbps' . IST_A0 . '  ' . $ulClr . $ulBar . IST_A0);
    }
    if ($ping !== null) {
        $pingClr = $ping <= 20 ? IST_ABGR : ($ping <= 60 ? IST_ABYE : IST_ABRE);
        $out    .= ist_row('Latency (Ping)', $pingClr . number_format($ping, 1) . ' ms' . IST_A0);
    }
    if ($jit !== null) {
        $jitClr = $jit <= 5 ? IST_ABGR : ($jit <= 20 ? IST_ABYE : IST_ABRE);
        $out   .= ist_row('Jitter',         $jitClr . number_format($jit, 1) . ' ms' . IST_A0);
    }
    if ($loss !== null) {
        $lossClr = $loss <= 1 ? IST_ABGR : ($loss <= 5 ? IST_ABYE : IST_ABRE);
        $out    .= ist_row('Packet Loss',   $lossClr . number_format($loss, 1) . '%' . IST_A0);
    }

    /* Timing Metrics */
    if (!empty($r['dns_ms']) || !empty($r['ttfb_ms']) || !empty($r['tls_ms'])) {
        $out .= ist_sec('Timing Metrics');
        if (!empty($r['dns_ms']))   $out .= ist_row('DNS Resolution',  number_format((float)$r['dns_ms'], 1)  . ' ms');
        if (!empty($r['tls_ms']))   $out .= ist_row('TLS Handshake',   number_format((float)$r['tls_ms'], 1)  . ' ms');
        if (!empty($r['ttfb_ms']))  $out .= ist_row('Time to 1st Byte',number_format((float)$r['ttfb_ms'], 1) . ' ms');
        if (!empty($r['http_ms']))  $out .= ist_row('HTTP Response',   number_format((float)$r['http_ms'], 1)  . ' ms');
    }

    /* Quality Scores */
    if (!empty($r['scores']) && is_array($r['scores'])) {
        $out .= ist_sec('Quality Scores');
        foreach ($r['scores'] as $name => $score) {
            $sc    = (int)$score;
            $grade = $sc >= 90 ? 'A+' : ($sc >= 80 ? 'A' : ($sc >= 65 ? 'B' : ($sc >= 50 ? 'C' : ($sc >= 35 ? 'D' : 'F'))));
            $clr   = ist_grade_clr($grade);
            $bar   = ist_bar($sc, 100, 18);
            $out  .= ist_row($name, $clr . IST_AB . str_pad($sc, 3) . '/100' . IST_A0 . '  ' . $clr . $bar . IST_A0 . '  ' . $clr . IST_AB . "Grade {$grade}" . IST_A0);
        }
    }

    /* Overall Grade */
    if (!empty($r['grade']) || !empty($r['score'])) {
        $out  .= ist_sec('Overall Assessment');
        $grade = $r['grade'] ?? '—';
        $score = isset($r['score']) ? (int)$r['score'] : null;
        $clr   = ist_grade_clr($grade);
        if ($score !== null) $out .= ist_row('Network Score', $clr . IST_AB . "{$score}/100" . IST_A0);
        $out .= ist_row('Connection Grade', $clr . IST_AB . $grade . IST_A0);
    }

    /* Environment */
    if (!empty($r['ip']) || !empty($r['user_agent']) || !empty($r['connection_type'])) {
        $out .= ist_sec('Environment');
        if (!empty($r['ip']))              $out .= ist_row('Client IP',       $r['ip']);
        if (!empty($r['connection_type'])) $out .= ist_row('Connection Type', $r['connection_type']);
        if (!empty($r['effective_type']))  $out .= ist_row('Effective Type',  $r['effective_type']);
        if (!empty($r['downlink']))        $out .= ist_row('Est. Downlink',   $r['downlink'] . ' Mbps');
        if (!empty($r['browser']))         $out .= ist_row('Browser',         $r['browser']);
        if (!empty($r['platform']))        $out .= ist_row('Platform',        $r['platform']);
    }

    /* Recommendations */
    $recs = $r['recommendations'] ?? [];
    if (empty($recs) && ($ping !== null || $dl !== null)) {
        // Auto-generate basic recommendations
        if ($ping !== null && $ping > 60)  $recs[] = 'High latency detected. Check for background processes using the network or consider a wired connection.';
        if ($jit  !== null && $jit  > 20)  $recs[] = 'Significant jitter observed. This may impact real-time applications like video calls and gaming.';
        if ($loss !== null && $loss > 2)   $recs[] = 'Packet loss above 2% detected. Check cables, router firmware, and contact your ISP if persistent.';
        if ($dl   !== null && $dl   < 25)  $recs[] = 'Download speed below 25 Mbps. Consider upgrading your plan or checking for network congestion.';
        if ($ul   !== null && $ul   < 5)   $recs[] = 'Upload speed is low. This may impact video calls, cloud uploads, and remote desktop performance.';
        if (empty($recs))                  $recs[] = 'Connection is performing well across all measured parameters.';
    }
    if (!empty($recs)) {
        $out .= ist_sec('Recommendations');
        foreach ($recs as $i => $rec) {
            $num  = IST_ABYE . IST_AB . ($i + 1) . '.' . IST_A0;
            $out .= "  {$num}  " . IST_AWH . wordwrap($rec, 58, "\n     ", true) . IST_A0 . "\n";
        }
    }

    $out .= ist_term_footer();
    echo $out;
    exit;
}

/* ─── Server Timings ─────────────────────────────────────────────────────── */
if ($action === 'server_timings') {
    header('Content-Type: application/json; charset=utf-8');

    $tStart = microtime(true);

    $result = [
        'php_version'    => PHP_VERSION,
        'sapi'           => PHP_SAPI,
        'server_time'    => gmdate('Y-m-d H:i:s') . ' UTC',
        'memory_peak_mb' => null,
        'exec_time_ms'   => null,
        'tcp_port80_ms'  => null,
        'tcp_port443_ms' => null,
    ];

    // Memory
    $result['memory_peak_mb'] = round(memory_get_peak_usage(true) / 1048576, 2);

    // TCP socket probes
    foreach ([80 => 'tcp_port80_ms', 443 => 'tcp_port443_ms'] as $port => $key) {
        $t0  = microtime(true);
        $sock = @fsockopen('8.8.8.8', $port, $errno, $errstr, 1);
        if ($sock) {
            $result[$key] = round((microtime(true) - $t0) * 1000, 1);
            fclose($sock);
        } else {
            $result[$key] = null;
        }
    }

    // Execution time (measured last)
    $result['exec_time_ms'] = round((microtime(true) - $tStart) * 1000, 2);

    echo json_encode($result);
    exit;
}

/* ─── Platform Latency Batch Ping (server-side HEAD requests via curl_multi) ─ */
if ($action === 'ping_batch') {
    header('Content-Type: application/json; charset=utf-8');

    $raw   = file_get_contents('php://input');
    $items = @json_decode($raw, true);
    if (!is_array($items) || !$items) {
        echo json_encode(['error' => 'No platforms supplied']); exit;
    }
    $items = array_slice($items, 0, 80);

    if (!function_exists('curl_multi_init')) {
        echo json_encode(['error' => 'curl_multi not available']); exit;
    }

    $mh      = curl_multi_init();
    $handles = [];

    foreach ($items as $i => $item) {
        if (empty($item['url'])) continue;
        $ch = curl_init((string)$item['url']);
        curl_setopt_array($ch, [
            CURLOPT_NOBODY         => true,
            CURLOPT_TIMEOUT        => 6,
            CURLOPT_CONNECTTIMEOUT => 4,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_SSL_VERIFYPEER => false,
            CURLOPT_SSL_VERIFYHOST => false,
            CURLOPT_FOLLOWLOCATION => true,
            CURLOPT_MAXREDIRS      => 2,
            CURLOPT_USERAGENT      => 'Mozilla/5.0 (compatible; IST/1.0; latency-probe)',
            CURLOPT_HTTPHEADER     => ['Accept: */*'],
        ]);
        $handles[$i] = ['ch' => $ch, 'id' => (string)($item['id'] ?? $i)];
        curl_multi_add_handle($mh, $ch);
    }

    $running = null;
    do {
        curl_multi_exec($mh, $running);
        if ($running > 0) curl_multi_select($mh, 0.05);
    } while ($running > 0);

    $results = [];
    foreach ($handles as $i => $entry) {
        $ch   = $entry['ch'];
        $id   = $entry['id'];
        $info = curl_getinfo($ch);
        $err  = curl_errno($ch);

        if (!$err && $info['http_code'] > 0) {
            /* starttransfer_time = time to first byte (true network latency for HEAD) */
            $starttransfer = isset($info['starttransfer_time_us'])
                ? $info['starttransfer_time_us'] / 1000.0
                : $info['starttransfer_time'] * 1000.0;
            $results[$id] = round(max(1.0, $starttransfer), 1);
        } else {
            $results[$id] = null;
        }

        curl_multi_remove_handle($mh, $ch);
        curl_close($ch);
    }
    curl_multi_close($mh);

    echo json_encode(['results' => $results]);
    exit;
}

/* ─── Network Path Analysis (traceroute-style via curl timing + TCP probes) ─ */
if ($action === 'traceroute') {
    header('Content-Type: application/json; charset=utf-8');

    $host = trim($_GET['host'] ?? '');
    if (!$host) { echo json_encode(['error' => 'No host specified']); exit; }

    // Strip protocol / path, keep only the hostname/IP portion
    $host = preg_replace('#^https?://#i', '', $host);
    $host = explode('/', $host)[0];
    $host = explode('?', $host)[0];
    $host = trim($host);

    // Strict allow-list: valid hostname or IPv4
    if (!preg_match('/^[a-zA-Z0-9.\-]{1,253}$/', $host) || strlen($host) < 2) {
        echo json_encode(['error' => 'Invalid host format. Use a domain name or IP address.']);
        exit;
    }

    // ── Stage 1: DNS resolution ──────────────────────────────────────────────
    $dnsT0  = microtime(true);
    $resolvedIp = gethostbyname($host);
    $dnsMs  = round((microtime(true) - $dnsT0) * 1000, 1);
    $dnsOk  = ($resolvedIp !== $host);

    // ── Stage 2: TCP connect probe (port 443, then 80) ───────────────────────
    $tcpMs = null; $tcpPort = null;
    foreach ([443, 80] as $port) {
        $t0   = microtime(true);
        $sock = @fsockopen($host, $port, $errno, $errstr, 1.5);
        if ($sock) {
            $tcpMs   = round((microtime(true) - $t0) * 1000, 1);
            $tcpPort = $port;
            fclose($sock);
            break;
        }
    }

    // ── Stage 3: Full curl timing breakdown ──────────────────────────────────
    $curlData = null;
    if (function_exists('curl_init')) {
        $proto = $tcpPort === 443 ? 'https' : 'http';
        $url   = $proto . '://' . $host . '/';
        $ch    = curl_init($url);
        curl_setopt_array($ch, [
            CURLOPT_NOBODY         => true,
            CURLOPT_FOLLOWLOCATION => true,
            CURLOPT_MAXREDIRS      => 3,
            CURLOPT_TIMEOUT        => 5,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_SSL_VERIFYPEER => false,
            CURLOPT_SSL_VERIFYHOST => false,
            CURLOPT_USERAGENT      => 'IST/1.0 (network-path-probe)',
            CURLOPT_HEADER         => true,
        ]);
        curl_exec($ch);
        $ci = curl_getinfo($ch);
        $curlErr = curl_error($ch);
        curl_close($ch);

        if (!$curlErr) {
            $curlData = [
                'dns_ms'       => round($ci['namelookup_time_us'] / 1000, 1),
                'tcp_ms'       => round(($ci['connect_time_us'] - $ci['namelookup_time_us']) / 1000, 1),
                'tls_ms'       => round(($ci['appconnect_time_us'] - $ci['connect_time_us']) / 1000, 1),
                'ttfb_ms'      => round(($ci['starttransfer_time_us'] - $ci['pretransfer_time_us']) / 1000, 1),
                'total_ms'     => round($ci['total_time_us'] / 1000, 1),
                'http_code'    => (int)$ci['http_code'],
                'content_type' => $ci['content_type'] ?? null,
                'ip'           => $ci['primary_ip'] ?? $resolvedIp,
                'port'         => (int)($ci['primary_port'] ?? $tcpPort),
                'redirect_count' => (int)$ci['redirect_count'],
                'redirect_url'   => $ci['redirect_url'] ?? null,
            ];
        }
    }

    // ── Stage 4: Probe well-known network waypoints (TCP) ────────────────────
    $waypoints = [
        ['label' => 'Cloudflare DNS',   'host' => '1.1.1.1',       'port' => 53,  'region' => 'Global Anycast'],
        ['label' => 'Google DNS',       'host' => '8.8.8.8',       'port' => 53,  'region' => 'Global Anycast'],
        ['label' => 'Cloudflare Edge',  'host' => '1.1.1.1',       'port' => 443, 'region' => 'CDN Edge'],
        ['label' => 'Google Edge',      'host' => '142.250.1.1',   'port' => 80,  'region' => 'Google Infrastructure'],
        ['label' => 'Fastly Edge',      'host' => '151.101.1.1',   'port' => 80,  'region' => 'CDN Edge'],
        ['label' => 'Akamai Edge',      'host' => '23.192.0.1',    'port' => 80,  'region' => 'CDN Edge'],
    ];

    // Parallel waypoint probing via curl_multi (all 6 run simultaneously)
    $wpResults = [];
    if (function_exists('curl_multi_init')) {
        $wmh = curl_multi_init();
        $wpHandles = [];
        foreach ($waypoints as $i => $wp) {
            $wproto = $wp['port'] === 443 ? 'https' : 'http';
            $wch    = curl_init($wproto . '://' . $wp['host'] . '/');
            curl_setopt_array($wch, [
                CURLOPT_NOBODY         => true,
                CURLOPT_TIMEOUT        => 3,
                CURLOPT_CONNECTTIMEOUT => 2,
                CURLOPT_SSL_VERIFYPEER => false,
                CURLOPT_SSL_VERIFYHOST => false,
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_USERAGENT      => 'IST/1.0 (waypoint-probe)',
            ]);
            $wpHandles[$i] = $wch;
            curl_multi_add_handle($wmh, $wch);
        }
        $wrunning = null;
        do {
            curl_multi_exec($wmh, $wrunning);
            if ($wrunning > 0) curl_multi_select($wmh, 0.05);
        } while ($wrunning > 0);
        foreach ($waypoints as $i => $wp) {
            $wch   = $wpHandles[$i];
            $winfo = curl_getinfo($wch);
            $werr  = curl_errno($wch);
            if (!$werr && $winfo['http_code'] > 0) {
                $connUs = $winfo['connect_time_us'] ?? (int)($winfo['connect_time'] * 1e6);
                $connMs = round($connUs / 1000, 1);
                $wpResults[] = array_merge($wp, ['ms' => $connMs, 'ok' => true]);
            } else {
                $wpResults[] = array_merge($wp, ['ms' => null, 'ok' => false]);
            }
            curl_multi_remove_handle($wmh, $wch);
            curl_close($wch);
        }
        curl_multi_close($wmh);
    } else {
        foreach ($waypoints as $wp) {
            $t0   = microtime(true);
            $sock = @fsockopen($wp['host'], $wp['port'], $errno, $errstr, 1);
            $ms   = round((microtime(true) - $t0) * 1000, 1);
            if ($sock) { fclose($sock); $ok = true; } else { $ok = false; $ms = null; }
            $wpResults[] = array_merge($wp, ['ms' => $ms, 'ok' => $ok]);
        }
    }

    // ── Build response ───────────────────────────────────────────────────────
    $hops = [];
    $hopN = 1;

    // DNS hop
    $hops[] = [
        'hop'   => $hopN++,
        'type'  => 'dns',
        'label' => 'DNS Resolution',
        'ip'    => $dnsOk ? $resolvedIp : null,
        'avg'   => $dnsOk ? $dnsMs : null,
        'note'  => $dnsOk ? 'Resolved to ' . $resolvedIp : 'DNS resolution failed',
        'ok'    => $dnsOk,
    ];

    // Waypoints
    foreach ($wpResults as $wp) {
        $hops[] = [
            'hop'   => $hopN++,
            'type'  => 'waypoint',
            'label' => $wp['label'],
            'ip'    => $wp['host'],
            'avg'   => $wp['ms'],
            'note'  => $wp['region'],
            'ok'    => $wp['ok'],
        ];
    }

    // TCP connect to target
    if ($tcpMs !== null) {
        $hops[] = [
            'hop'   => $hopN++,
            'type'  => 'tcp',
            'label' => 'TCP Connect → ' . $host,
            'ip'    => $resolvedIp,
            'avg'   => $tcpMs,
            'note'  => 'Port ' . $tcpPort . ' · direct TCP handshake',
            'ok'    => true,
        ];
    }

    // Curl stages (only if we got timing data)
    if ($curlData) {
        if ($curlData['tls_ms'] > 0) {
            $hops[] = [
                'hop'   => $hopN++,
                'type'  => 'tls',
                'label' => 'TLS Handshake',
                'ip'    => $curlData['ip'],
                'avg'   => $curlData['tls_ms'],
                'note'  => 'SSL/TLS negotiation',
                'ok'    => true,
            ];
        }
        $hops[] = [
            'hop'   => $hopN++,
            'type'  => 'ttfb',
            'label' => 'Server Response',
            'ip'    => null,
            'avg'   => $curlData['ttfb_ms'],
            'note'  => 'HTTP ' . $curlData['http_code'] . ' · first byte received',
            'ok'    => $curlData['http_code'] > 0,
        ];
    }

    echo json_encode([
        'host'       => $host,
        'ip'         => $dnsOk ? $resolvedIp : null,
        'hops'       => $hops,
        'total'      => count($hops),
        'curl'       => $curlData,
        'mode'       => 'tcp_analysis',
    ]);
    exit;
}

/* ─── DNS Propagation Checker ────────────────────────────────────────────── */
if ($action === 'dns_propagation') {
    header('Content-Type: application/json; charset=utf-8');

    $domain = strtolower(trim($_GET['domain'] ?? ''));
    $type   = strtoupper(trim($_GET['type']   ?? 'A'));

    if (!$domain) { echo json_encode(['error' => 'No domain specified']); exit; }

    // Strip protocol / path
    $domain = preg_replace('#^https?://#i', '', $domain);
    $domain = explode('/', $domain)[0];
    $domain = explode(':', $domain)[0];

    if (!preg_match('/^[a-zA-Z0-9.\-]{2,253}$/', $domain)) {
        echo json_encode(['error' => 'Invalid domain format. Use a bare domain like example.com']); exit;
    }

    $allowed = ['A','AAAA','MX','TXT','CNAME','NS','SOA','PTR','SRV','CAA'];
    if (!in_array($type, $allowed)) $type = 'A';

    $resolvers = [
        ['name'=>'Cloudflare',  'url'=>'https://1.1.1.1/dns-query',            'region'=>'Global (Anycast)',  'org'=>'Cloudflare'],
        ['name'=>'Google',      'url'=>'https://dns.google/resolve',            'region'=>'Global (Anycast)',  'org'=>'Google'],
        ['name'=>'Quad9',       'url'=>'https://dns.quad9.net/dns-query',       'region'=>'Switzerland',       'org'=>'Quad9'],
        ['name'=>'OpenDNS',     'url'=>'https://doh.opendns.com/dns-query',     'region'=>'San Jose, US',      'org'=>'Cisco'],
        ['name'=>'AdGuard',     'url'=>'https://dns.adguard-dns.com/resolve',   'region'=>'Cyprus',            'org'=>'AdGuard'],
        ['name'=>'NextDNS',     'url'=>'https://dns.nextdns.io/dns-query',      'region'=>'Global (Anycast)',  'org'=>'NextDNS'],
        ['name'=>'Mullvad',     'url'=>'https://dns.mullvad.net/dns-query',     'region'=>'Sweden',            'org'=>'Mullvad'],
        ['name'=>'CleanBrowsing','url'=>'https://doh.cleanbrowsing.org/doh/family-filter/', 'region'=>'USA', 'org'=>'CleanBrowsing'],
    ];

    if (!function_exists('curl_multi_init')) {
        echo json_encode(['error' => 'curl_multi not available']); exit;
    }

    $mh      = curl_multi_init();
    $handles = [];
    foreach ($resolvers as $i => $r) {
        $url = $r['url'] . '?name=' . urlencode($domain) . '&type=' . urlencode($type);
        $ch  = curl_init($url);
        curl_setopt_array($ch, [
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_TIMEOUT        => 8,
            CURLOPT_CONNECTTIMEOUT => 4,
            CURLOPT_FOLLOWLOCATION => true,
            CURLOPT_MAXREDIRS      => 2,
            CURLOPT_SSL_VERIFYPEER => false,
            CURLOPT_HTTPHEADER     => ['Accept: application/dns-json'],
            CURLOPT_USERAGENT      => 'IST/1.0 (dns-probe)',
        ]);
        $handles[$i] = $ch;
        curl_multi_add_handle($mh, $ch);
    }

    $running = null;
    do { curl_multi_exec($mh, $running); usleep(8000); } while ($running > 0);

    $results = [];
    foreach ($resolvers as $i => $r) {
        $body    = curl_multi_getcontent($handles[$i]);
        $info    = curl_getinfo($handles[$i]);
        $latMs   = round($info['total_time'] * 1000, 1);
        $answers = [];
        $status  = 'error';
        $rcode   = null;

        if ($body) {
            $parsed = json_decode($body, true);
            if (is_array($parsed) && array_key_exists('Status', $parsed)) {
                $rcode = (int)$parsed['Status'];
                if ($rcode === 0 && !empty($parsed['Answer'])) {
                    $status = 'ok';
                    foreach ($parsed['Answer'] as $ans) {
                        if (isset($ans['data'])) {
                            $answers[] = [
                                'data' => $ans['data'],
                                'ttl'  => isset($ans['TTL']) ? (int)$ans['TTL'] : null,
                                'type' => isset($ans['type']) ? (int)$ans['type'] : null,
                            ];
                        }
                    }
                } elseif ($rcode === 3) {
                    $status = 'nxdomain';
                } elseif ($rcode === 0) {
                    $status = 'nodata';
                } else {
                    $status = 'servfail';
                }
            }
        }

        if ($info['total_time'] == 0 || ($info['http_code'] == 0 && $latMs < 50)) {
            $status = 'timeout'; $latMs = null;
        }

        $results[] = [
            'resolver' => $r['name'],
            'org'      => $r['org'],
            'region'   => $r['region'],
            'status'   => $status,
            'latency'  => $latMs,
            'answers'  => $answers,
            'rcode'    => $rcode,
        ];

        curl_multi_remove_handle($mh, $handles[$i]);
        curl_close($handles[$i]);
    }
    curl_multi_close($mh);

    // Check consistency
    $answerSets = array_map(function($r) {
        $vals = array_map(function($a) { return $a['data']; }, $r['answers']);
        sort($vals);
        return implode(',', $vals);
    }, array_filter($results, function($r) { return $r['status'] === 'ok'; }));
    $consistent = count(array_unique($answerSets)) <= 1;

    echo json_encode([
        'domain'     => $domain,
        'type'       => $type,
        'resolvers'  => $results,
        'consistent' => $consistent,
        'ok_count'   => count(array_filter($results, function($r) { return $r['status']==='ok'; })),
        'total'      => count($results),
    ]);
    exit;
}


/* ─── Deep Latency Analyzer ──────────────────────────────────────────────── */
/*
 * action=latency_analyze
 *
 * POST params:
 *   url             — target URL (required)
 *   count           — number of probes, 3-30, default 10
 *   method          — HTTP method: HEAD (default) or GET
 *   conn_timeout    — TCP connect timeout in seconds, 1-30, default 5
 *   req_timeout     — total request timeout in seconds, 2-60, default 10
 *   follow_redirects— "1" to follow, "0" to not, default "1"
 */
if ($action === 'latency_analyze') {
    header('Content-Type: application/json; charset=utf-8');

    /* ── Input validation ───────────────────────────────────────────────── */
    $rawUrl   = trim($_POST['url']  ?? $_GET['url']  ?? '');
    $count    = min(max((int)($_POST['count']        ?? $_GET['count']        ?? 10), 3), 30);
    $method   = strtoupper(trim($_POST['method']     ?? $_GET['method']       ?? 'HEAD'));
    $connTout = min(max((int)($_POST['conn_timeout'] ?? $_GET['conn_timeout'] ?? 5),  1), 30);
    $reqTout  = min(max((int)($_POST['req_timeout']  ?? $_GET['req_timeout']  ?? 10), 2), 60);
    $followR  = ($_POST['follow_redirects'] ?? $_GET['follow_redirects'] ?? '1') !== '0';

    if (!$rawUrl) { echo json_encode(['ok'=>false,'error'=>'URL is required.']); exit; }
    if (!preg_match('#^https?://#i', $rawUrl)) $rawUrl = 'https://' . $rawUrl;
    if (!filter_var($rawUrl, FILTER_VALIDATE_URL)) {
        echo json_encode(['ok'=>false,'error'=>'Invalid URL format.']); exit;
    }
    $parsedUrl = parse_url($rawUrl);
    $host = $parsedUrl['host'] ?? '';
    if (!$host) { echo json_encode(['ok'=>false,'error'=>'Cannot extract host from URL.']); exit; }
    if (!in_array($method, ['HEAD','GET','OPTIONS'])) $method = 'HEAD';
    if (!function_exists('curl_init')) {
        echo json_encode(['ok'=>false,'error'=>'cURL extension not available on this server.']); exit;
    }

    /* ── DNS resolution (fresh, measured separately) ────────────────────── */
    $dnsT0     = function_exists('hrtime') ? hrtime(true) : (int)(microtime(true) * 1e9);
    $resolvedIp = @gethostbyname($host);
    $dnsT1     = function_exists('hrtime') ? hrtime(true) : (int)(microtime(true) * 1e9);
    $freshDnsMs = round(($dnsT1 - $dnsT0) / 1e6, 3);
    $dnsOk     = ($resolvedIp !== $host && filter_var($resolvedIp, FILTER_VALIDATE_IP));
    if (!$dnsOk) {
        echo json_encode(['ok'=>false,'error'=>"DNS resolution failed for '{$host}'. Check the hostname and try again."]); exit;
    }

    $scheme       = strtolower($parsedUrl['scheme'] ?? 'https');
    $port         = $parsedUrl['port'] ?? ($scheme === 'https' ? 443 : 80);
    $resolveEntry = "{$host}:{$port}:{$resolvedIp}";

    /* ── Helper: build a single cURL handle ─────────────────────────────── */
    function ist_la_build(string $url, string $method, int $ct, int $rt, bool $fresh, string $re, bool $follow): CurlHandle {
        $ch = curl_init($url);
        $opts = [
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_HEADER         => true,
            CURLOPT_NOBODY         => ($method === 'HEAD'),
            CURLOPT_CUSTOMREQUEST  => $method,
            CURLOPT_CONNECTTIMEOUT => $ct,
            CURLOPT_TIMEOUT        => $rt,
            CURLOPT_FOLLOWLOCATION => $follow,
            CURLOPT_MAXREDIRS      => 3,
            CURLOPT_SSL_VERIFYPEER => false,
            CURLOPT_SSL_VERIFYHOST => 0,
            CURLOPT_USERAGENT      => 'Mozilla/5.0 (compatible; AwanTools-LatencyAnalyzer/2.0; +https://awantools.site)',
            CURLOPT_HTTPHEADER     => ['Accept: */*','Connection: keep-alive','Cache-Control: no-cache'],
        ];
        /* For non-fresh probes, inject pre-resolved IP to bypass DNS cost */
        if (!$fresh) $opts[CURLOPT_RESOLVE] = [$re];
        curl_setopt_array($ch, $opts);
        return $ch;
    }

    /* ── Helper: extract µs-accurate timing from curl_getinfo ───────────── */
    function ist_la_timing(array $i): array {
        $us = isset($i['namelookup_time_us']); // PHP 7.3+ / curl 7.61+
        $ms = fn(string $k) => $us ? ($i[$k.'_us'] ?? 0) / 1000.0 : ($i[$k] ?? 0.0) * 1000.0;

        $dns   = $ms('namelookup_time');
        $conn  = $ms('connect_time');
        $app   = $ms('appconnect_time');   // 0 for plain HTTP
        $pre   = $ms('pretransfer_time');
        $stx   = $ms('starttransfer_time');
        $total = $ms('total_time');

        return [
            'dns_ms'      => round($dns,                         3),
            'tcp_ms'      => round(max(0, $conn - $dns),         3),
            'tls_ms'      => round($app > 0 ? max(0,$app-$conn) : 0.0, 3),
            'ttfb_ms'     => round(max(0, $stx - $pre),         3),
            'transfer_ms' => round(max(0, $total - $stx),       3),
            'total_ms'    => round($total,                       3),
            'http_code'   => (int)($i['http_code'] ?? 0),
        ];
    }

    /* ── Helper: extract response metadata ──────────────────────────────── */
    function ist_la_meta(array $i, string $rawResp): array {
        $hdrSize = (int)($i['header_size'] ?? 0);
        $hdrs    = [];
        foreach (explode("\r\n", substr($rawResp, 0, $hdrSize)) as $line) {
            if (strpos($line, ':') !== false) {
                [$k, $v] = explode(':', $line, 2);
                $hdrs[strtolower(trim($k))] = trim($v);
            }
        }
        $hvMap = [10=>'HTTP/1.0', 11=>'HTTP/1.1', 20=>'HTTP/2', 30=>'HTTP/3', 0=>'Unknown'];
        $hv    = $hvMap[$i['http_version'] ?? 0] ?? ('HTTP/'.(int)($i['http_version']??0));
        return [
            'ip'             => $i['primary_ip']             ?? null,
            'port'           => (int)($i['primary_port']     ?? 0),
            'http_code'      => (int)($i['http_code']        ?? 0),
            'http_version'   => $hv,
            'content_type'   => $i['content_type']           ?? null,
            'content_length' => (int)($i['download_content_length'] ?? -1),
            'redirect_count' => (int)($i['redirect_count']   ?? 0),
            'redirect_url'   => ($i['redirect_url']          ?? '') ?: null,
            'scheme'         => $i['scheme']                 ?? null,
            'ssl_verify'     => (int)($i['ssl_verify_result'] ?? -1),
            'server'         => $hdrs['server']              ?? null,
            'x_powered_by'   => $hdrs['x-powered-by']       ?? null,
            'cache_control'  => $hdrs['cache-control']       ?? null,
            'x_cache'        => $hdrs['x-cache-status'] ?? $hdrs['x-cache'] ?? null,
            'cf_ray'         => $hdrs['cf-ray']              ?? null,
            'via'            => $hdrs['via']                 ?? null,
        ];
    }

    /* ── Statistics ─────────────────────────────────────────────────────── */
    function ist_la_stats(array $vals): array {
        if (!$vals) return array_fill_keys(['min','max','avg','median','stddev','jitter','p95'], 0.0);
        sort($vals);
        $n      = count($vals);
        $min    = $vals[0]; $max = $vals[$n-1];
        $avg    = array_sum($vals) / $n;
        $mid    = (int)($n / 2);
        $median = ($n%2===0) ? ($vals[$mid-1]+$vals[$mid])/2.0 : $vals[$mid];
        $stddev = sqrt(array_sum(array_map(fn($v)=>($v-$avg)**2, $vals))/$n);
        $diffs  = [];
        for ($j=1;$j<$n;$j++) $diffs[]=abs($vals[$j]-$vals[$j-1]);
        $jitter = $diffs ? array_sum($diffs)/count($diffs) : 0.0;
        $p95    = $vals[max(0,min((int)ceil(0.95*$n)-1,$n-1))];
        return [
            'min'=>round($min,3),'max'=>round($max,3),'avg'=>round($avg,3),
            'median'=>round($median,3),'stddev'=>round($stddev,3),
            'jitter'=>round($jitter,3),'p95'=>round($p95,3),
        ];
    }

    /* ── Outlier removal (IQR method) ───────────────────────────────────── */
    function ist_la_deoutlier(array $probes, string $key): array {
        if (count($probes) <= 4) return ['filtered'=>$probes,'removed'=>0];
        $vals = array_column($probes, $key); sort($vals); $n = count($vals);
        $q1 = $vals[(int)floor(($n-1)*0.25)];
        $q3 = $vals[(int)floor(($n-1)*0.75)];
        $iqr = $q3 - $q1;
        $lo  = $q1 - 1.5*$iqr;  $hi = $q3 + 1.5*$iqr;
        $out = array_values(array_filter($probes, fn($p) => isset($p[$key]) && $p[$key]>=$lo && $p[$key]<=$hi));
        return ['filtered'=>$out,'removed'=>count($probes)-count($out)];
    }

    /* ── Per-segment stats helper ───────────────────────────────────────── */
    function ist_la_segstats(array $probes, string $key): array {
        $vals = array_values(array_filter(array_column($probes, $key), fn($v)=>is_numeric($v)));
        if (!$vals) return ['avg'=>null,'min'=>null,'max'=>null,'samples'=>0];
        $s = ist_la_stats($vals); $s['samples'] = count($vals); return $s;
    }

    /* ── Color-coded rating ─────────────────────────────────────────────── */
    function ist_la_rate(float $ms, array $t): array {
        [$exc,$good,$fair] = $t;
        if ($ms<=$exc)  return ['label'=>'Excellent','cls'=>'excellent','score'=>100];
        if ($ms<=$good) return ['label'=>'Good','cls'=>'good','score'=>(int)(75+25*(1-($ms-$exc)/max(1,$good-$exc)))];
        if ($ms<=$fair) return ['label'=>'Fair','cls'=>'fair','score'=>(int)(50+25*(1-($ms-$good)/max(1,$fair-$good)))];
        return ['label'=>'Poor','cls'=>'poor','score'=>max(0,(int)(50*(1-min(1,($ms-$fair)/max(1,$fair)))))];
    }

    /* ── SQLite history (stored in sys temp dir) ────────────────────────── */
    function ist_la_db(): ?PDO {
        try {
            $f   = sys_get_temp_dir() . '/ist_latency_v2.db';
            $pdo = new PDO('sqlite:'.$f);
            $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
            $pdo->exec('CREATE TABLE IF NOT EXISTS history (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                url TEXT NOT NULL, tested_at INTEGER NOT NULL,
                count INTEGER, method TEXT,
                avg_ms REAL, min_ms REAL, max_ms REAL, median_ms REAL,
                stddev_ms REAL, jitter_ms REAL, p95_ms REAL, packet_loss REAL,
                dns_ms REAL, tcp_ms REAL, tls_ms REAL, ttfb_ms REAL,
                ip TEXT, http_code INTEGER, http_version TEXT, rating TEXT
            )');
            return $pdo;
        } catch (Exception $e) { return null; }
    }

    function ist_la_save(string $url, array $r): int {
        $pdo = ist_la_db(); if (!$pdo) return 0;
        try {
            $s = $r['stats']; $sg = $r['segments']; $m = $r['meta'] ?? [];
            $pdo->prepare(
                'INSERT INTO history (url,tested_at,count,method,avg_ms,min_ms,max_ms,median_ms,
                 stddev_ms,jitter_ms,p95_ms,packet_loss,dns_ms,tcp_ms,tls_ms,ttfb_ms,
                 ip,http_code,http_version,rating) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)'
            )->execute([
                $url, time(), $r['count'], $r['method'],
                $s['avg'], $s['min'], $s['max'], $s['median'],
                $s['stddev'], $s['jitter'], $s['p95'], $s['packet_loss'],
                $sg['dns']['avg'] ?? null, $sg['tcp']['avg'] ?? null,
                $sg['tls']['avg'] ?? null, $sg['ttfb']['avg'] ?? null,
                $m['ip'] ?? null, $m['http_code'] ?? null, $m['http_version'] ?? null,
                $r['ratings']['overall']['label'] ?? null,
            ]);
            return (int)$pdo->lastInsertId();
        } catch (Exception $e) { return 0; }
    }

    function ist_la_history(string $url, int $limit = 10): array {
        $pdo = ist_la_db(); if (!$pdo) return [];
        try {
            $st = $pdo->prepare(
                'SELECT id,tested_at,avg_ms,min_ms,max_ms,median_ms,jitter_ms,p95_ms,
                        packet_loss,dns_ms,ttfb_ms,http_code,rating
                   FROM history WHERE url=? ORDER BY tested_at DESC LIMIT ?'
            );
            $st->execute([$url, $limit]);
            return $st->fetchAll(PDO::FETCH_ASSOC);
        } catch (Exception $e) { return []; }
    }

    /* ═══════════════════════════════════════════════════════════════════════
     * MEASUREMENT LOOP
     * ═══════════════════════════════════════════════════════════════════════ */
    $wallStart = function_exists('hrtime') ? hrtime(true) : (int)(microtime(true)*1e9);
    $probes    = [];
    $meta      = null;
    $failed    = 0;

    /* ── Probe 1: fresh, serial — collects headers + metadata ───────────── */
    {
        $ch  = ist_la_build($rawUrl, $method, $connTout, $reqTout, true, $resolveEntry, $followR);
        $raw = curl_exec($ch);
        $inf = curl_getinfo($ch);
        $err = curl_errno($ch);
        $em  = $err ? curl_error($ch) : null;
        curl_close($ch);

        if (!$err && $inf['http_code'] > 0) {
            $t = ist_la_timing($inf);
            $t['n'] = 1; $t['ok'] = true; $t['is_fresh'] = true; $t['error'] = null;
            $probes[] = $t;
            $meta = ist_la_meta($inf, is_string($raw) ? $raw : '');
        } else {
            $failed++;
            $probes[] = ['n'=>1,'ok'=>false,'is_fresh'=>true,'error'=>$em];
        }
    }

    /* ── Probes 2-N: parallel via curl_multi in batches of 10 ───────────── */
    if ($count > 1) {
        if (function_exists('curl_multi_init')) {
            $remaining = $count - 1;
            $pIdx      = 2;
            $batchSize = min(10, $remaining);

            while ($remaining > 0) {
                $batch   = min($batchSize, $remaining);
                $mh      = curl_multi_init();
                $handles = [];
                for ($b = 0; $b < $batch; $b++) {
                    $ch = ist_la_build($rawUrl, $method, $connTout, $reqTout, false, $resolveEntry, $followR);
                    $handles[] = ['ch'=>$ch, 'n'=>$pIdx++];
                    curl_multi_add_handle($mh, $ch);
                }
                $running = null;
                do {
                    curl_multi_exec($mh, $running);
                    if ($running > 0) curl_multi_select($mh, 0.01);
                } while ($running > 0);

                foreach ($handles as $entry) {
                    $ch  = $entry['ch'];
                    $inf = curl_getinfo($ch);
                    $err = curl_errno($ch);
                    $em  = $err ? curl_error($ch) : null;
                    if (!$err && $inf['http_code'] > 0) {
                        $t = ist_la_timing($inf);
                        $t['n']=$entry['n']; $t['ok']=true; $t['is_fresh']=false; $t['error']=null;
                        $probes[] = $t;
                        if (!$meta) {
                            $raw  = curl_multi_getcontent($ch);
                            $meta = ist_la_meta($inf, is_string($raw)?$raw:'');
                        }
                    } else {
                        $failed++;
                        $probes[] = ['n'=>$entry['n'],'ok'=>false,'is_fresh'=>false,'error'=>$em];
                    }
                    curl_multi_remove_handle($mh, $ch);
                    curl_close($ch);
                }
                curl_multi_close($mh);
                $remaining -= $batch;
            }
        } else {
            /* Fallback: sequential probes when curl_multi unavailable */
            for ($i = 2; $i <= $count; $i++) {
                $ch  = ist_la_build($rawUrl, $method, $connTout, $reqTout, false, $resolveEntry, $followR);
                $raw = curl_exec($ch);
                $inf = curl_getinfo($ch);
                $err = curl_errno($ch);
                $em  = $err ? curl_error($ch) : null;
                curl_close($ch);
                if (!$err && $inf['http_code']>0) {
                    $t=ist_la_timing($inf); $t['n']=$i; $t['ok']=true; $t['is_fresh']=false; $t['error']=null;
                    $probes[]=$t;
                } else {
                    $failed++;
                    $probes[]=['n'=>$i,'ok'=>false,'is_fresh'=>false,'error'=>$em];
                }
            }
        }
    }

    /* ── Post-processing ────────────────────────────────────────────────── */
    $succeeded   = array_values(array_filter($probes, fn($p)=>$p['ok']));
    $packetLoss  = $count>0 ? round(($failed/$count)*100,1) : 100.0;
    $outlierInfo = ist_la_deoutlier($succeeded, 'total_ms');
    $clean       = $outlierInfo['filtered'];
    $outRmvd     = $outlierInfo['removed'];

    /* Per-segment statistics (on outlier-cleaned probes) */
    $segments = [
        'dns'      => ist_la_segstats($clean, 'dns_ms'),
        'tcp'      => ist_la_segstats($clean, 'tcp_ms'),
        'tls'      => ist_la_segstats($clean, 'tls_ms'),
        'ttfb'     => ist_la_segstats($clean, 'ttfb_ms'),
        'transfer' => ist_la_segstats($clean, 'transfer_ms'),
        'total'    => ist_la_segstats($clean, 'total_ms'),
    ];

    /* Overall latency statistics */
    $totalVals = array_column($clean, 'total_ms');
    $stats     = ist_la_stats($totalVals);
    $stats['packet_loss']      = $packetLoss;
    $stats['samples']          = $count;
    $stats['succeeded']        = count($succeeded);
    $stats['failed']           = $failed;
    $stats['outliers_removed'] = $outRmvd;
    $stats['dns_fresh_ms']     = $freshDnsMs;

    /* Ratings */
    $ratings = [
        'overall' => ist_la_rate($stats['avg']               ?? 999, [50,  100, 200]),
        'ttfb'    => ist_la_rate($segments['ttfb']['avg']    ?? 999, [20,   50, 100]),
        'dns'     => ist_la_rate($segments['dns']['avg']     ?? 999, [10,   30, 100]),
        'tcp'     => ist_la_rate($segments['tcp']['avg']     ?? 999, [20,   50, 150]),
        'tls'     => ist_la_rate($segments['tls']['avg']     ?? 999, [30,   80, 200]),
    ];

    $wallEnd    = function_exists('hrtime') ? hrtime(true) : (int)(microtime(true)*1e9);
    $durationMs = round(($wallEnd - $wallStart)/1e6, 1);

    /* ── Assemble result ────────────────────────────────────────────────── */
    $result = [
        'ok'          => true,
        'url'         => $rawUrl,
        'host'        => $host,
        'count'       => $count,
        'method'      => $method,
        'duration_ms' => $durationMs,
        'meta'        => $meta ?? [],
        'segments'    => $segments,
        'stats'       => $stats,
        'ratings'     => $ratings,
        'probes'      => $probes,
        'timestamp'   => time(),
    ];

    /* Store in SQLite and attach history */
    $history        = ist_la_history($rawUrl, 9);
    $result['saved_id'] = ist_la_save($rawUrl, $result);
    $result['history']  = $history;

    echo json_encode($result);
    exit;
}

/* ─── Latency history lookup ─────────────────────────────────────────────── */
if ($action === 'latency_history') {
    header('Content-Type: application/json; charset=utf-8');
    $rawUrl = trim($_GET['url'] ?? '');
    if (!$rawUrl) { echo json_encode(['ok'=>false,'error'=>'url required']); exit; }
    if (!preg_match('#^https?://#i', $rawUrl)) $rawUrl = 'https://' . $rawUrl;
    /* Reuse ist_la_db / ist_la_history if latency_analyze was already called */
    if (!function_exists('ist_la_db')) {
        function ist_la_db(): ?PDO {
            try {
                $f=$p=sys_get_temp_dir().'/ist_latency_v2.db';
                $pdo=new PDO('sqlite:'.$f);
                $pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);
                $pdo->exec('CREATE TABLE IF NOT EXISTS history (
                    id INTEGER PRIMARY KEY AUTOINCREMENT, url TEXT NOT NULL,
                    tested_at INTEGER NOT NULL, count INTEGER, method TEXT,
                    avg_ms REAL, min_ms REAL, max_ms REAL, median_ms REAL,
                    stddev_ms REAL, jitter_ms REAL, p95_ms REAL, packet_loss REAL,
                    dns_ms REAL, tcp_ms REAL, tls_ms REAL, ttfb_ms REAL,
                    ip TEXT, http_code INTEGER, http_version TEXT, rating TEXT)');
                return $pdo;
            } catch (Exception $e) { return null; }
        }
        function ist_la_history(string $url, int $limit=10): array {
            $pdo=ist_la_db(); if (!$pdo) return [];
            try {
                $st=$pdo->prepare(
                    'SELECT id,tested_at,avg_ms,min_ms,max_ms,median_ms,jitter_ms,p95_ms,
                            packet_loss,dns_ms,ttfb_ms,http_code,rating
                       FROM history WHERE url=? ORDER BY tested_at DESC LIMIT ?');
                $st->execute([$url,$limit]); return $st->fetchAll(PDO::FETCH_ASSOC);
            } catch (Exception $e) { return []; }
        }
    }
    echo json_encode(['ok'=>true,'url'=>$rawUrl,'history'=>ist_la_history($rawUrl,20)]);
    exit;
}

/* ─── Unknown action ─────────────────────────────────────────────────────── */
header('Content-Type: application/json; charset=utf-8');
echo json_encode(['error' => 'Unknown action: ' . htmlspecialchars($action)]);
exit;
